### ISSUE TITLE
User import

### ISSUE THREAD

**Issue by kliptonize** [kliptonize/skematik#15]
An organisation-admin can bulk-import users (possibly via csv) or create them in the back-end, one by one, just with an emailaddress, and perhaps a role or some sort of access to certain tables?

Also, make the front-end view.

**Comment by kliptonize** [comment]
Also, I'd need a GET-call "/users" or smthng that returns all granted users for the organisation of the user :D

**Comment by kliptonize** [comment]
Optie om "@mijnschool.be"-adressen standaard toe te laten?

**Comment by EveraertJan** [comment]
bulk csv import opened

**Comment by kliptonize** [comment]
Works works works works works works

**Comment by EveraertJan** [comment]
aw yiss
