### ISSUE TITLE
Fetch users call

### ISSUE THREAD

**Issue by kliptonize** [kliptonize/skematik#17]
Also, I'd need a GET-call "/users" or smthng that returns all granted users for the organisation of the user :D

**Comment by kliptonize** [comment]
Front-end view ready

**Comment by EveraertJan** [comment]
all there

**Comment by kliptonize** [comment]
Dus:
- get/put-call nodig /participants (name, mail, status, [role, role], uuid)`get` haalt alle participants op, `put` ontvangt alle data opnieuw, met updates en mogelijk nieuwe participants (uuid: null)

**Comment by EveraertJan** [comment]
updated

**Comment by kliptonize** [comment]
Done!
